# -*- coding: utf-8 -*-
"""
Adaptive outer solver for the one-dimensional LATIN-PGD algorithm.

For every LATIN iteration, the solver performs:

1. nonlinear local stage;
2. PGD global stage using the current spatial basis;
3. relaxation of the global candidate;
4. evaluation of the relative LATIN indicator xi_(i+1);
5. evaluation of the saturation parameter

       zeta = (xi_i - xi_(i+1)) / (xi_i + xi_(i+1));

6. acceptance of the global state or enrichment of the PGD basis.

The reference indicator xi_i is the indicator accepted at the preceding
LATIN iteration.  It is kept fixed while additional PGD pairs are generated
inside the current global stage.  For the first iteration, xi_0 is initialised
to 1.0, which is the natural normalised reference value.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional, Sequence, Tuple

import numpy as np
from numpy.typing import NDArray

from fem.bar_1d import BarMesh1D
from latin.iteration_control import (
    relative_latin_indicator,
    relax_global_state,
)
from latin.local_stage import solve_local_stage
from latin.pgd_basis import PGDBasis1D
from latin.pgd_global_stage import (
    PGDGlobalStageResult,
    solve_pgd_global_stage,
)
from latin.pgd_saturation import decide_pgd_saturation
from latin.search_directions import (
    DescentSearchDirections,
    compute_descent_search_directions,
)
from latin.state import LatinState
from material.viscoplastic_damage_1d import MaterialParameters


FloatArray = NDArray[np.float64]
IntArray = NDArray[np.int64]


class PGDTerminationReason(Enum):
    """Reason for terminating the adaptive LATIN-PGD solver."""

    CONVERGED = "converged"
    SATURATED = "saturated"
    MAX_ITERATIONS = "max_iterations"
    MAX_ENRICHMENTS = "max_enrichments"
    ENRICHMENT_FAILED = "enrichment_failed"


@dataclass(frozen=True)
class PGDLatinResult:
    """Final state, reduced basis and adaptive convergence history."""

    state: LatinState
    local_state: LatinState
    directions: DescentSearchDirections
    basis: PGDBasis1D
    indicator_history: FloatArray
    baseline_indicator_history: FloatArray
    trial_indicator_history: FloatArray
    saturation_history: FloatArray
    trial_basis_size_history: IntArray
    trial_reduced_residual_history: FloatArray
    modes_added_history: IntArray
    converged: bool
    saturated: bool
    iterations: int
    trial_evaluations: int
    termination_reason: PGDTerminationReason
    tolerance: float
    relaxation: float
    saturation_enrichment_tolerance: float
    saturation_stopping_tolerance: float

    @property
    def final_indicator(self) -> float:
        """Return the last accepted relative LATIN indicator."""
        if self.indicator_history.size > 0:
            return float(self.indicator_history[-1])
        return float(self.baseline_indicator_history[-1])

    @property
    def total_modes_added(self) -> int:
        """Return the number of PGD modes generated by this solve."""
        return int(np.sum(self.modes_added_history))


def _validate_solver_inputs(
    initial_state: LatinState,
    mesh: BarMesh1D,
    area: float,
    materials: Sequence[MaterialParameters],
    initial_basis: Optional[PGDBasis1D],
    initial_indicator: float,
    tolerance: float,
    max_iterations: int,
    relaxation: float,
    saturation_enrichment_tolerance: float,
    saturation_stopping_tolerance: float,
    reduced_tolerance: float,
    max_enrichments_per_iteration: int,
    search_regularization: float,
    fixed_point_tolerance: float,
    max_fixed_point_iterations: int,
    minimum_spatial_norm: float,
    acceptance_tolerance: float,
    rcond: float,
) -> None:
    """Validate the discretisation and adaptive control parameters."""
    if area <= 0.0:
        raise ValueError("area must be positive.")
    if initial_state.n_elements != mesh.n_elements:
        raise ValueError(
            "initial_state and mesh must contain the same "
            "number of elements."
        )
    if len(materials) != mesh.n_elements:
        raise ValueError(
            "One MaterialParameters object is required per element."
        )

    if initial_basis is not None:
        if initial_basis.field_shape != initial_state.field_shape:
            raise ValueError(
                "initial_basis and initial_state must use the same "
                "space-time grid."
            )

    if initial_indicator <= 0.0 or not np.isfinite(
        initial_indicator
    ):
        raise ValueError(
            "initial_indicator must be positive and finite."
        )
    if tolerance <= 0.0 or not np.isfinite(tolerance):
        raise ValueError("tolerance must be positive and finite.")
    if max_iterations < 1:
        raise ValueError("max_iterations must be at least one.")
    if not 0.0 < relaxation <= 1.0:
        raise ValueError(
            "relaxation must satisfy 0 < relaxation <= 1."
        )

    if (
        saturation_enrichment_tolerance <= 0.0
        or not np.isfinite(saturation_enrichment_tolerance)
    ):
        raise ValueError(
            "saturation_enrichment_tolerance must be positive "
            "and finite."
        )
    if (
        saturation_stopping_tolerance < 0.0
        or not np.isfinite(saturation_stopping_tolerance)
    ):
        raise ValueError(
            "saturation_stopping_tolerance must be non-negative "
            "and finite."
        )
    if (
        saturation_stopping_tolerance
        >= saturation_enrichment_tolerance
    ):
        raise ValueError(
            "saturation_stopping_tolerance must be smaller than "
            "saturation_enrichment_tolerance."
        )

    if reduced_tolerance <= 0.0 or not np.isfinite(
        reduced_tolerance
    ):
        raise ValueError(
            "reduced_tolerance must be positive and finite."
        )
    if max_enrichments_per_iteration < 1:
        raise ValueError(
            "max_enrichments_per_iteration must be at least one."
        )
    if search_regularization <= 0.0 or not np.isfinite(
        search_regularization
    ):
        raise ValueError(
            "search_regularization must be positive and finite."
        )
    if fixed_point_tolerance <= 0.0 or not np.isfinite(
        fixed_point_tolerance
    ):
        raise ValueError(
            "fixed_point_tolerance must be positive and finite."
        )
    if max_fixed_point_iterations < 1:
        raise ValueError(
            "max_fixed_point_iterations must be at least one."
        )
    if minimum_spatial_norm <= 0.0 or not np.isfinite(
        minimum_spatial_norm
    ):
        raise ValueError(
            "minimum_spatial_norm must be positive and finite."
        )
    if acceptance_tolerance < 0.0 or not np.isfinite(
        acceptance_tolerance
    ):
        raise ValueError(
            "acceptance_tolerance must be non-negative and finite."
        )
    if rcond <= 0.0 or not np.isfinite(rcond):
        raise ValueError("rcond must be positive and finite.")


def _build_result(
    *,
    state: LatinState,
    local_state: LatinState,
    directions: DescentSearchDirections,
    basis: PGDBasis1D,
    indicator_values: Sequence[float],
    baseline_indicator_values: Sequence[float],
    trial_indicator_values: Sequence[float],
    saturation_values: Sequence[float],
    trial_basis_sizes: Sequence[int],
    trial_reduced_residual_values: Sequence[float],
    modes_added_values: Sequence[int],
    converged: bool,
    saturated: bool,
    iterations: int,
    termination_reason: PGDTerminationReason,
    tolerance: float,
    relaxation: float,
    saturation_enrichment_tolerance: float,
    saturation_stopping_tolerance: float,
) -> PGDLatinResult:
    """Create an immutable result from accumulated Python histories."""
    return PGDLatinResult(
        state=state,
        local_state=local_state,
        directions=directions,
        basis=basis,
        indicator_history=np.asarray(
            indicator_values,
            dtype=np.float64,
        ),
        baseline_indicator_history=np.asarray(
            baseline_indicator_values,
            dtype=np.float64,
        ),
        trial_indicator_history=np.asarray(
            trial_indicator_values,
            dtype=np.float64,
        ),
        saturation_history=np.asarray(
            saturation_values,
            dtype=np.float64,
        ),
        trial_basis_size_history=np.asarray(
            trial_basis_sizes,
            dtype=np.int64,
        ),
        trial_reduced_residual_history=np.asarray(
            trial_reduced_residual_values,
            dtype=np.float64,
        ),
        modes_added_history=np.asarray(
            modes_added_values,
            dtype=np.int64,
        ),
        converged=converged,
        saturated=saturated,
        iterations=iterations,
        trial_evaluations=len(trial_indicator_values),
        termination_reason=termination_reason,
        tolerance=float(tolerance),
        relaxation=float(relaxation),
        saturation_enrichment_tolerance=float(
            saturation_enrichment_tolerance
        ),
        saturation_stopping_tolerance=float(
            saturation_stopping_tolerance
        ),
    )


def _evaluate_relaxed_candidate(
    previous_global_state: LatinState,
    local_state: LatinState,
    directions: DescentSearchDirections,
    global_stage_result: PGDGlobalStageResult,
    mesh: BarMesh1D,
    area: float,
    materials: Sequence[MaterialParameters],
    relaxation: float,
) -> Tuple[LatinState, float]:
    """Relax one PGD global candidate and evaluate its LATIN indicator."""
    relaxed_state = relax_global_state(
        previous_state=previous_global_state,
        candidate_state=global_stage_result.state,
        relaxation=relaxation,
    )
    indicator = relative_latin_indicator(
        local_state=local_state,
        global_state=relaxed_state,
        directions=directions,
        mesh=mesh,
        area=area,
        materials=materials,
    )

    if not np.isfinite(indicator):
        raise FloatingPointError(
            "The LATIN indicator became non-finite."
        )

    return relaxed_state, float(indicator)


def solve_latin_pgd(
    initial_state: LatinState,
    mesh: BarMesh1D,
    area: float,
    materials: Sequence[MaterialParameters],
    *,
    initial_basis: Optional[PGDBasis1D] = None,
    initial_indicator: float = 1.0,
    tolerance: float = 1.0e-3,
    max_iterations: int = 50,
    relaxation: float = 0.8,
    saturation_enrichment_tolerance: float = 0.1,
    saturation_stopping_tolerance: float = 1.0e-4,
    reduced_tolerance: float = 1.0e-4,
    max_enrichments_per_iteration: int = 10,
    search_regularization: float = 0.15,
    fixed_point_tolerance: float = 1.0e-6,
    max_fixed_point_iterations: int = 30,
    minimum_spatial_norm: float = 1.0e-14,
    acceptance_tolerance: float = 1.0e-8,
    rcond: float = 1.0e-12,
) -> PGDLatinResult:
    """
    Run adaptive LATIN-PGD iterations over the complete time-space domain.

    ``initial_indicator`` supplies xi_0 before the first LATIN iteration.
    After an iteration is accepted, its current indicator becomes the
    reference xi_i for the next iteration.  During basis enrichment inside
    one global stage, this reference remains unchanged.
    """
    _validate_solver_inputs(
        initial_state=initial_state,
        mesh=mesh,
        area=area,
        materials=materials,
        initial_basis=initial_basis,
        initial_indicator=initial_indicator,
        tolerance=tolerance,
        max_iterations=max_iterations,
        relaxation=relaxation,
        saturation_enrichment_tolerance=(
            saturation_enrichment_tolerance
        ),
        saturation_stopping_tolerance=(
            saturation_stopping_tolerance
        ),
        reduced_tolerance=reduced_tolerance,
        max_enrichments_per_iteration=(
            max_enrichments_per_iteration
        ),
        search_regularization=search_regularization,
        fixed_point_tolerance=fixed_point_tolerance,
        max_fixed_point_iterations=max_fixed_point_iterations,
        minimum_spatial_norm=minimum_spatial_norm,
        acceptance_tolerance=acceptance_tolerance,
        rcond=rcond,
    )

    global_state = initial_state.copy()

    if initial_basis is None:
        basis = PGDBasis1D(
            n_elements=initial_state.n_elements,
            n_time=initial_state.time.size,
        )
    else:
        basis = initial_basis.copy()

    indicator_values = []
    baseline_indicator_values = []
    trial_indicator_values = []
    saturation_values = []
    trial_basis_sizes = []
    trial_reduced_residual_values = []
    modes_added_values = []

    completed_iterations = 0
    previous_indicator = float(initial_indicator)
    last_local_state = initial_state.copy()
    last_directions: Optional[DescentSearchDirections] = None

    for latin_iteration in range(1, max_iterations + 1):
        local_state = solve_local_stage(
            global_state=global_state,
            materials=materials,
        )
        directions = compute_descent_search_directions(
            local_state=local_state,
            materials=materials,
            regularization=search_regularization,
        )
        last_local_state = local_state
        last_directions = directions
        baseline_indicator_values.append(previous_indicator)

        # An empty spatial basis cannot perform a time-only update.
        # Therefore, the first PGD pair is generated before evaluating zeta.
        force_first_pair = basis.n_modes == 0

        global_stage_result = solve_pgd_global_stage(
            global_state=global_state,
            local_state=local_state,
            directions=directions,
            mesh=mesh,
            area=area,
            materials=materials,
            basis=basis,
            reduced_tolerance=reduced_tolerance,
            max_new_modes=1 if force_first_pair else 0,
            allow_enrichment=force_first_pair,
            latin_iteration=latin_iteration,
            fixed_point_tolerance=fixed_point_tolerance,
            max_fixed_point_iterations=(
                max_fixed_point_iterations
            ),
            minimum_spatial_norm=minimum_spatial_norm,
            acceptance_tolerance=acceptance_tolerance,
            rcond=rcond,
        )

        basis = global_stage_result.basis
        enrichments_this_iteration = (
            global_stage_result.modes_added
        )

        if force_first_pair and enrichments_this_iteration == 0:
            return _build_result(
                state=global_state,
                local_state=last_local_state,
                directions=directions,
                basis=basis,
                indicator_values=indicator_values,
                baseline_indicator_values=(
                    baseline_indicator_values
                ),
                trial_indicator_values=trial_indicator_values,
                saturation_values=saturation_values,
                trial_basis_sizes=trial_basis_sizes,
                trial_reduced_residual_values=(
                    trial_reduced_residual_values
                ),
                modes_added_values=modes_added_values,
                converged=False,
                saturated=False,
                iterations=completed_iterations,
                termination_reason=(
                    PGDTerminationReason.ENRICHMENT_FAILED
                ),
                tolerance=tolerance,
                relaxation=relaxation,
                saturation_enrichment_tolerance=(
                    saturation_enrichment_tolerance
                ),
                saturation_stopping_tolerance=(
                    saturation_stopping_tolerance
                ),
            )

        while True:
            candidate_state, current_indicator = (
                _evaluate_relaxed_candidate(
                    previous_global_state=global_state,
                    local_state=local_state,
                    directions=directions,
                    global_stage_result=global_stage_result,
                    mesh=mesh,
                    area=area,
                    materials=materials,
                    relaxation=relaxation,
                )
            )

            decision = decide_pgd_saturation(
                previous_indicator=previous_indicator,
                current_indicator=current_indicator,
                enrichment_tolerance=(
                    saturation_enrichment_tolerance
                ),
                stopping_tolerance=(
                    saturation_stopping_tolerance
                ),
            )

            trial_indicator_values.append(current_indicator)
            saturation_values.append(decision.value)
            trial_basis_sizes.append(basis.n_modes)
            trial_reduced_residual_values.append(
                global_stage_result.relative_residual
            )

            if current_indicator <= tolerance:
                global_state = candidate_state
                completed_iterations += 1
                indicator_values.append(current_indicator)
                modes_added_values.append(
                    enrichments_this_iteration
                )

                return _build_result(
                    state=global_state,
                    local_state=last_local_state,
                    directions=directions,
                    basis=basis,
                    indicator_values=indicator_values,
                    baseline_indicator_values=(
                        baseline_indicator_values
                    ),
                    trial_indicator_values=(
                        trial_indicator_values
                    ),
                    saturation_values=saturation_values,
                    trial_basis_sizes=trial_basis_sizes,
                    trial_reduced_residual_values=(
                        trial_reduced_residual_values
                    ),
                    modes_added_values=modes_added_values,
                    converged=True,
                    saturated=False,
                    iterations=completed_iterations,
                    termination_reason=(
                        PGDTerminationReason.CONVERGED
                    ),
                    tolerance=tolerance,
                    relaxation=relaxation,
                    saturation_enrichment_tolerance=(
                        saturation_enrichment_tolerance
                    ),
                    saturation_stopping_tolerance=(
                        saturation_stopping_tolerance
                    ),
                )

            if decision.should_advance_latin:
                global_state = candidate_state
                completed_iterations += 1
                indicator_values.append(current_indicator)
                modes_added_values.append(
                    enrichments_this_iteration
                )
                previous_indicator = current_indicator
                break

            if decision.should_stop:
                global_state = candidate_state
                completed_iterations += 1
                indicator_values.append(current_indicator)
                modes_added_values.append(
                    enrichments_this_iteration
                )

                return _build_result(
                    state=global_state,
                    local_state=last_local_state,
                    directions=directions,
                    basis=basis,
                    indicator_values=indicator_values,
                    baseline_indicator_values=(
                        baseline_indicator_values
                    ),
                    trial_indicator_values=(
                        trial_indicator_values
                    ),
                    saturation_values=saturation_values,
                    trial_basis_sizes=trial_basis_sizes,
                    trial_reduced_residual_values=(
                        trial_reduced_residual_values
                    ),
                    modes_added_values=modes_added_values,
                    converged=False,
                    saturated=True,
                    iterations=completed_iterations,
                    termination_reason=(
                        PGDTerminationReason.SATURATED
                    ),
                    tolerance=tolerance,
                    relaxation=relaxation,
                    saturation_enrichment_tolerance=(
                        saturation_enrichment_tolerance
                    ),
                    saturation_stopping_tolerance=(
                        saturation_stopping_tolerance
                    ),
                )

            # The saturation rule may request another PGD mode even
            # though the current reduced global problem is already solved
            # to the prescribed reduced tolerance. In that situation no
            # non-zero residual remains from which a useful mode can be
            # generated. Accept the current candidate and continue with the
            # next nonlinear LATIN iteration instead of reporting a false
            # enrichment failure.
            if (
                global_stage_result.relative_residual
                <= reduced_tolerance
            ):
                global_state = candidate_state
                completed_iterations += 1
                indicator_values.append(current_indicator)
                modes_added_values.append(
                    enrichments_this_iteration
                )
                previous_indicator = current_indicator
                break

            if (
                enrichments_this_iteration
                >= max_enrichments_per_iteration
            ):
                global_state = candidate_state
                completed_iterations += 1
                indicator_values.append(current_indicator)
                modes_added_values.append(
                    enrichments_this_iteration
                )

                return _build_result(
                    state=global_state,
                    local_state=last_local_state,
                    directions=directions,
                    basis=basis,
                    indicator_values=indicator_values,
                    baseline_indicator_values=(
                        baseline_indicator_values
                    ),
                    trial_indicator_values=(
                        trial_indicator_values
                    ),
                    saturation_values=saturation_values,
                    trial_basis_sizes=trial_basis_sizes,
                    trial_reduced_residual_values=(
                        trial_reduced_residual_values
                    ),
                    modes_added_values=modes_added_values,
                    converged=False,
                    saturated=False,
                    iterations=completed_iterations,
                    termination_reason=(
                        PGDTerminationReason.MAX_ENRICHMENTS
                    ),
                    tolerance=tolerance,
                    relaxation=relaxation,
                    saturation_enrichment_tolerance=(
                        saturation_enrichment_tolerance
                    ),
                    saturation_stopping_tolerance=(
                        saturation_stopping_tolerance
                    ),
                )

            enriched_result = solve_pgd_global_stage(
                global_state=global_state,
                local_state=local_state,
                directions=directions,
                mesh=mesh,
                area=area,
                materials=materials,
                basis=basis,
                reduced_tolerance=reduced_tolerance,
                max_new_modes=1,
                allow_enrichment=True,
                latin_iteration=latin_iteration,
                fixed_point_tolerance=(
                    fixed_point_tolerance
                ),
                max_fixed_point_iterations=(
                    max_fixed_point_iterations
                ),
                minimum_spatial_norm=minimum_spatial_norm,
                acceptance_tolerance=acceptance_tolerance,
                rcond=rcond,
            )

            if enriched_result.modes_added == 0:
                global_state = candidate_state
                completed_iterations += 1
                indicator_values.append(current_indicator)
                modes_added_values.append(
                    enrichments_this_iteration
                )

                return _build_result(
                    state=global_state,
                    local_state=last_local_state,
                    directions=directions,
                    basis=basis,
                    indicator_values=indicator_values,
                    baseline_indicator_values=(
                        baseline_indicator_values
                    ),
                    trial_indicator_values=(
                        trial_indicator_values
                    ),
                    saturation_values=saturation_values,
                    trial_basis_sizes=trial_basis_sizes,
                    trial_reduced_residual_values=(
                        trial_reduced_residual_values
                    ),
                    modes_added_values=modes_added_values,
                    converged=False,
                    saturated=False,
                    iterations=completed_iterations,
                    termination_reason=(
                        PGDTerminationReason.ENRICHMENT_FAILED
                    ),
                    tolerance=tolerance,
                    relaxation=relaxation,
                    saturation_enrichment_tolerance=(
                        saturation_enrichment_tolerance
                    ),
                    saturation_stopping_tolerance=(
                        saturation_stopping_tolerance
                    ),
                )

            global_stage_result = enriched_result
            basis = global_stage_result.basis
            enrichments_this_iteration += (
                global_stage_result.modes_added
            )

    if last_directions is None:
        raise RuntimeError(
            "The LATIN-PGD solver terminated before its first iteration."
        )

    return _build_result(
        state=global_state,
        local_state=last_local_state,
        directions=last_directions,
        basis=basis,
        indicator_values=indicator_values,
        baseline_indicator_values=baseline_indicator_values,
        trial_indicator_values=trial_indicator_values,
        saturation_values=saturation_values,
        trial_basis_sizes=trial_basis_sizes,
        trial_reduced_residual_values=(
            trial_reduced_residual_values
        ),
        modes_added_values=modes_added_values,
        converged=False,
        saturated=False,
        iterations=completed_iterations,
        termination_reason=(
            PGDTerminationReason.MAX_ITERATIONS
        ),
        tolerance=tolerance,
        relaxation=relaxation,
        saturation_enrichment_tolerance=(
            saturation_enrichment_tolerance
        ),
        saturation_stopping_tolerance=(
            saturation_stopping_tolerance
        ),
    )
